project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: About Data
        file: about.qmd
      - text: Related Research
        file: research.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true


resources:
  - data/
  - images/
  - analysis.ipynb
