project:
  type: website
  output-dir: docs

website:
  title: "Data Release"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: flatly
    css: styles.css
    toc: true


resources:
  - data/matters.csv
  - data/hearings.csv
  - images/** 
  - analysis.ipynb