project:
  type: website
  output-dir: docs

website:
  title: "data_release"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

resources:
  - bhc_data.csv
